# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EstudianteRn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EstudianteRn.proto',
  package='estudiantern',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x45studianteRn.proto\x12\x0c\x65studiantern\"&\n\x11\x45studianteRequest\x12\x11\n\tmatricula\x18\x01 \x01(\x05\"H\n\x12\x45studianteResponse\x12\x11\n\tmatricula\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rrera\x18\x03 \x01(\t\"\x1f\n\x11\x45studianteBorrado\x12\n\n\x02ok\x18\x01 \x01(\x08\"G\n\x0fListaEstudiante\x12\x34\n\nestudiante\x18\x01 \x03(\x0b\x32 .estudiantern.EstudianteResponse\"\x07\n\x05\x45mpty\">\n\x0bMensajeChat\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x03 \x01(\t2\x85\x04\n\x0c\x45studianteRn\x12R\n\rgetEstudiante\x12\x1f.estudiantern.EstudianteRequest\x1a .estudiantern.EstudianteResponse\x12U\n\x0f\x63rearEstudiante\x12 .estudiantern.EstudianteResponse\x1a .estudiantern.EstudianteResponse\x12Z\n\x14\x61\x63tualizarEstudiante\x12 .estudiantern.EstudianteResponse\x1a .estudiantern.EstudianteResponse\x12V\n\x12\x65liminarEstudiante\x12\x1f.estudiantern.EstudianteRequest\x1a\x1f.estudiantern.EstudianteBorrado\x12\x45\n\x0flistaEstudiante\x12\x13.estudiantern.Empty\x1a\x1d.estudiantern.ListaEstudiante\x12O\n\x13\x63hatEntreEstudiante\x12\x19.estudiantern.MensajeChat\x1a\x19.estudiantern.MensajeChat(\x01\x30\x01\x62\x06proto3'
)




_ESTUDIANTEREQUEST = _descriptor.Descriptor(
  name='EstudianteRequest',
  full_name='estudiantern.EstudianteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matricula', full_name='estudiantern.EstudianteRequest.matricula', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=74,
)


_ESTUDIANTERESPONSE = _descriptor.Descriptor(
  name='EstudianteResponse',
  full_name='estudiantern.EstudianteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matricula', full_name='estudiantern.EstudianteResponse.matricula', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='estudiantern.EstudianteResponse.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='carrera', full_name='estudiantern.EstudianteResponse.carrera', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=148,
)


_ESTUDIANTEBORRADO = _descriptor.Descriptor(
  name='EstudianteBorrado',
  full_name='estudiantern.EstudianteBorrado',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='estudiantern.EstudianteBorrado.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=181,
)


_LISTAESTUDIANTE = _descriptor.Descriptor(
  name='ListaEstudiante',
  full_name='estudiantern.ListaEstudiante',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='estudiante', full_name='estudiantern.ListaEstudiante.estudiante', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=254,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='estudiantern.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=263,
)


_MENSAJECHAT = _descriptor.Descriptor(
  name='MensajeChat',
  full_name='estudiantern.MensajeChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='estudiantern.MensajeChat.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='estudiantern.MensajeChat.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fecha', full_name='estudiantern.MensajeChat.fecha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=327,
)

_LISTAESTUDIANTE.fields_by_name['estudiante'].message_type = _ESTUDIANTERESPONSE
DESCRIPTOR.message_types_by_name['EstudianteRequest'] = _ESTUDIANTEREQUEST
DESCRIPTOR.message_types_by_name['EstudianteResponse'] = _ESTUDIANTERESPONSE
DESCRIPTOR.message_types_by_name['EstudianteBorrado'] = _ESTUDIANTEBORRADO
DESCRIPTOR.message_types_by_name['ListaEstudiante'] = _LISTAESTUDIANTE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MensajeChat'] = _MENSAJECHAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstudianteRequest = _reflection.GeneratedProtocolMessageType('EstudianteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ESTUDIANTEREQUEST,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.EstudianteRequest)
  })
_sym_db.RegisterMessage(EstudianteRequest)

EstudianteResponse = _reflection.GeneratedProtocolMessageType('EstudianteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ESTUDIANTERESPONSE,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.EstudianteResponse)
  })
_sym_db.RegisterMessage(EstudianteResponse)

EstudianteBorrado = _reflection.GeneratedProtocolMessageType('EstudianteBorrado', (_message.Message,), {
  'DESCRIPTOR' : _ESTUDIANTEBORRADO,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.EstudianteBorrado)
  })
_sym_db.RegisterMessage(EstudianteBorrado)

ListaEstudiante = _reflection.GeneratedProtocolMessageType('ListaEstudiante', (_message.Message,), {
  'DESCRIPTOR' : _LISTAESTUDIANTE,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.ListaEstudiante)
  })
_sym_db.RegisterMessage(ListaEstudiante)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.Empty)
  })
_sym_db.RegisterMessage(Empty)

MensajeChat = _reflection.GeneratedProtocolMessageType('MensajeChat', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJECHAT,
  '__module__' : 'EstudianteRn_pb2'
  # @@protoc_insertion_point(class_scope:estudiantern.MensajeChat)
  })
_sym_db.RegisterMessage(MensajeChat)



_ESTUDIANTERN = _descriptor.ServiceDescriptor(
  name='EstudianteRn',
  full_name='estudiantern.EstudianteRn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=330,
  serialized_end=847,
  methods=[
  _descriptor.MethodDescriptor(
    name='getEstudiante',
    full_name='estudiantern.EstudianteRn.getEstudiante',
    index=0,
    containing_service=None,
    input_type=_ESTUDIANTEREQUEST,
    output_type=_ESTUDIANTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='crearEstudiante',
    full_name='estudiantern.EstudianteRn.crearEstudiante',
    index=1,
    containing_service=None,
    input_type=_ESTUDIANTERESPONSE,
    output_type=_ESTUDIANTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='actualizarEstudiante',
    full_name='estudiantern.EstudianteRn.actualizarEstudiante',
    index=2,
    containing_service=None,
    input_type=_ESTUDIANTERESPONSE,
    output_type=_ESTUDIANTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='eliminarEstudiante',
    full_name='estudiantern.EstudianteRn.eliminarEstudiante',
    index=3,
    containing_service=None,
    input_type=_ESTUDIANTEREQUEST,
    output_type=_ESTUDIANTEBORRADO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listaEstudiante',
    full_name='estudiantern.EstudianteRn.listaEstudiante',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LISTAESTUDIANTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='chatEntreEstudiante',
    full_name='estudiantern.EstudianteRn.chatEntreEstudiante',
    index=5,
    containing_service=None,
    input_type=_MENSAJECHAT,
    output_type=_MENSAJECHAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTUDIANTERN)

DESCRIPTOR.services_by_name['EstudianteRn'] = _ESTUDIANTERN

# @@protoc_insertion_point(module_scope)
