# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import EstudianteRn_pb2 as EstudianteRn__pb2


class EstudianteRnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getEstudiante = channel.unary_unary(
                '/estudiantern.EstudianteRn/getEstudiante',
                request_serializer=EstudianteRn__pb2.EstudianteRequest.SerializeToString,
                response_deserializer=EstudianteRn__pb2.EstudianteResponse.FromString,
                )
        self.crearEstudiante = channel.unary_unary(
                '/estudiantern.EstudianteRn/crearEstudiante',
                request_serializer=EstudianteRn__pb2.EstudianteResponse.SerializeToString,
                response_deserializer=EstudianteRn__pb2.EstudianteResponse.FromString,
                )
        self.actualizarEstudiante = channel.unary_unary(
                '/estudiantern.EstudianteRn/actualizarEstudiante',
                request_serializer=EstudianteRn__pb2.EstudianteResponse.SerializeToString,
                response_deserializer=EstudianteRn__pb2.EstudianteResponse.FromString,
                )
        self.eliminarEstudiante = channel.unary_unary(
                '/estudiantern.EstudianteRn/eliminarEstudiante',
                request_serializer=EstudianteRn__pb2.EstudianteRequest.SerializeToString,
                response_deserializer=EstudianteRn__pb2.EstudianteBorrado.FromString,
                )
        self.listaEstudiante = channel.unary_unary(
                '/estudiantern.EstudianteRn/listaEstudiante',
                request_serializer=EstudianteRn__pb2.Empty.SerializeToString,
                response_deserializer=EstudianteRn__pb2.ListaEstudiante.FromString,
                )
        self.chatEntreEstudiante = channel.stream_stream(
                '/estudiantern.EstudianteRn/chatEntreEstudiante',
                request_serializer=EstudianteRn__pb2.MensajeChat.SerializeToString,
                response_deserializer=EstudianteRn__pb2.MensajeChat.FromString,
                )


class EstudianteRnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def crearEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def actualizarEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def eliminarEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listaEstudiante(self, request, context):
        """utilizando los formatos predefinidos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def chatEntreEstudiante(self, request_iterator, context):
        """servicio para implementar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstudianteRnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.getEstudiante,
                    request_deserializer=EstudianteRn__pb2.EstudianteRequest.FromString,
                    response_serializer=EstudianteRn__pb2.EstudianteResponse.SerializeToString,
            ),
            'crearEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.crearEstudiante,
                    request_deserializer=EstudianteRn__pb2.EstudianteResponse.FromString,
                    response_serializer=EstudianteRn__pb2.EstudianteResponse.SerializeToString,
            ),
            'actualizarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.actualizarEstudiante,
                    request_deserializer=EstudianteRn__pb2.EstudianteResponse.FromString,
                    response_serializer=EstudianteRn__pb2.EstudianteResponse.SerializeToString,
            ),
            'eliminarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.eliminarEstudiante,
                    request_deserializer=EstudianteRn__pb2.EstudianteRequest.FromString,
                    response_serializer=EstudianteRn__pb2.EstudianteBorrado.SerializeToString,
            ),
            'listaEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.listaEstudiante,
                    request_deserializer=EstudianteRn__pb2.Empty.FromString,
                    response_serializer=EstudianteRn__pb2.ListaEstudiante.SerializeToString,
            ),
            'chatEntreEstudiante': grpc.stream_stream_rpc_method_handler(
                    servicer.chatEntreEstudiante,
                    request_deserializer=EstudianteRn__pb2.MensajeChat.FromString,
                    response_serializer=EstudianteRn__pb2.MensajeChat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estudiantern.EstudianteRn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EstudianteRn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estudiantern.EstudianteRn/getEstudiante',
            EstudianteRn__pb2.EstudianteRequest.SerializeToString,
            EstudianteRn__pb2.EstudianteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def crearEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estudiantern.EstudianteRn/crearEstudiante',
            EstudianteRn__pb2.EstudianteResponse.SerializeToString,
            EstudianteRn__pb2.EstudianteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def actualizarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estudiantern.EstudianteRn/actualizarEstudiante',
            EstudianteRn__pb2.EstudianteResponse.SerializeToString,
            EstudianteRn__pb2.EstudianteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def eliminarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estudiantern.EstudianteRn/eliminarEstudiante',
            EstudianteRn__pb2.EstudianteRequest.SerializeToString,
            EstudianteRn__pb2.EstudianteBorrado.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listaEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estudiantern.EstudianteRn/listaEstudiante',
            EstudianteRn__pb2.Empty.SerializeToString,
            EstudianteRn__pb2.ListaEstudiante.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def chatEntreEstudiante(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/estudiantern.EstudianteRn/chatEntreEstudiante',
            EstudianteRn__pb2.MensajeChat.SerializeToString,
            EstudianteRn__pb2.MensajeChat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
